In [2]:
import numpy as np
a=np.array([10,20,30,40,50])
print("One dimensional array:",a)

One dimensional array: [10 20 30 40 50]


In [4]:
import numpy as np
b=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("Two dimensional array:",b)

Two dimensional array: [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [5]:
import numpy as np
c=np.zeros((3,5))
print("\n Array with all zeros:\n",c)


 Array with all zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
import numpy as np
d=np.random.random((3,3))
print("\n Random value:\n",d)


 Random value:
 [[0.35507195 0.81209456 0.8294121 ]
 [0.77540669 0.63444027 0.34330152]
 [0.32895178 0.86875831 0.01788786]]


In [8]:
import numpy  as np
e=np.arange(0,100,5)
print("\n Range value:\n",e)


 Range value:
 [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [9]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newarr=arr.reshape((4,3))
print("\n Original array:\n",arr)
print("\n Reshaped array [4,3]:\n", newarr)


 Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 Reshaped array [4,3]:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [17]:
#program 7.1
import numpy as np
c=np.zeros((5,3))
print("\n Array with all zeros\n",c)

#program 7.2
import numpy as rnp
r=rnp.random.random((5,3))
print("\n Array with random values/n",r)
print("\n No. of dimensions:",arr.ndim)

#program 7.3
import numpy as snp
s=snp.arange(0,105,5)
print("\n Strip size array \n",s)

#program 7.4
arr=rnp.array([[1,2,3],[5,6,7],[9,10,11],[13,14,15],[17,18,19]])
newarr=arr.reshape(3,5)
print("\n Reshaped array\n",newarr)


 Array with all zeros
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 Array with random values/n [[0.98179856 0.9309802  0.36974099]
 [0.40027905 0.85439897 0.30231673]
 [0.26512575 0.05748828 0.27946706]
 [0.78200031 0.81602014 0.04409677]
 [0.88573047 0.3286429  0.87819358]]

 No. of dimensions: 2

 Strip size array 
 [  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]

 Reshaped array
 [[ 1  2  3  5  6]
 [ 7  9 10 11 13]
 [14 15 17 18 19]]


In [20]:
#program 8
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
flat=arr.flatten()
print("Flattened array\n",flat)

Flattened array
 [1 2 3 4 5 6 7 8 9]


In [12]:
#program 9
import numpy as rnp
r=rnp.random.random((5,2))
print("\n No.of dimensions:",r.ndim)


 No.of dimensions: 2


In [9]:
#program 10
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print("\n shape of array:",a.shape)


 shape of array: (5, 3)


In [18]:
#program 11
import numpy as a
arr=a.array([1,2,3])
newtype=arr.astype("f")
print("\n convert array element:\n",newtype)
print("convert array:",newtype.dtype)


 convert array element:
 [1. 2. 3.]
convert array: float32


In [24]:
#program 12
import numpy as a
arr=a.array([1,2,3])
size=len(arr)
print("\n Size of the array:\n",size)


 Size of the array:
 3
